In [1]:
import numpy as np
import astropy
import statistics
from scipy import stats as scistats
from scipy.stats import wilcoxon
from scipy.stats import binomtest
from scipy.stats import f_oneway
from scipy.stats import ttest_ind
from scipy.stats import mannwhitneyu
from scipy.stats import friedmanchisquare
import scikit_posthocs as sp
from scipy.stats import shapiro

from astropy import stats
from statistics import multimode

In [2]:
correct = np.load('correct.npy') #Counts of correct answers by question
experts_correct = np.load('experts_correct.npy')
nonexperts_correct = np.load('nonexperts_correct.npy')
astromus_correct = np.load('astromus_correct.npy')
mus_correct = np.load('mus_correct.npy')
astro_correct = np.load('astro_correct.npy')
nonexperts_4_correct = np.load('nonexperts_4_correct.npy')
blv_correct = np.load('blv_correct.npy')
nonblv_correct = np.load('nonblv_correct.npy')

In [3]:
grades = np.load('grades.npy') #Counts of correct answers by participant
grades_experts = np.load('grades_experts.npy')
grades_nonexperts = np.load('grades_nonexperts.npy')
grades_astromus = np.load('grades_astromus.npy')
grades_mus = np.load('grades_mus.npy')
grades_astro = np.load('grades_astro.npy')
grades_nonexperts_4 = np.load('grades_nonexperts_4.npy')
grades_nonblv = np.load('grades_nonblv.npy')
grades_nonblv = np.load('grades_nonblv.npy')

In [4]:
combined_correct = np.load('combined_correct.npy')
experts_combined_correct = np.load('experts_combined_correct.npy')
nonexperts_combined_correct = np.load('nonexperts_combined_correct.npy')
astromus_combined_correct = np.load('astromus_combined_correct.npy')
mus_combined_correct = np.load('mus_combined_correct.npy')
astro_combined_correct = np.load('astro_combined_correct.npy')
nonexperts_4_combined_correct = np.load('nonexperts_4_combined_correct.npy')
blv_combined_correct = np.load('blv_combined_correct.npy')
nonblv_combined_correct = np.load('nonblv_combined_correct.npy')

In [5]:
groups = ["Global", "Experienced", "Non-experienced", "Astro", "Mus", "Astromus", "Nothing","BLV", "Non-BLV-2"]
counts = [correct, experts_correct, nonexperts_correct, astro_correct, mus_correct, astromus_correct, nonexperts_4_correct]
participants = np.load('participants.npy')

In [6]:
questions = len(correct)
questions

12

In [7]:
null_value = 0.34

# Statistics

In [8]:
#mean, median, mode
def calculations(counts, participants, questions):
    print("Participants:", participants)
    print(counts)
    mean = np.round(np.mean(counts/participants), 4) #overall average success rate
    median = np.round(np.median(counts/participants), 4) #median 
    mode = multimode(np.round(counts, 2))
    return mean, median, mode

In [9]:
null_value

0.34

In [10]:
# Wilcoxon test. Calculates if the observed overall average success rate
#is statistically significantly higher than chance.

def wilcoxon_test(counts, participants, null_value):
    observed_proportions = [x/participants for x in counts]
    # Compute differences from the null value
    differences = [x - null_value for x in observed_proportions]
    # Perform the Wilcoxon signed-rank test
    # alternative='greater' tests whether the median is significantly greater than the null
    test_statistic, p_value = wilcoxon(differences, alternative='greater')
    # Output results
    print("Success rates:", observed_proportions)
    print("Test statistic (W):", test_statistic)
    print("p-value (one-sided):", p_value)
    if p_value <= 0.05:
        print("Conclusion: Statistically significant")
    else:
        print("Conclusion: Not statistically significant")
    return test_statistic, p_value

In [11]:
# Alternative Binomial test
def binom_test(counts, participants, questions, null_value, less_or_greater):
    questions = questions-2
    test = binomtest(np.sum(counts), participants*questions, p=null_value, alternative=less_or_greater)
    if test.pvalue<0.05:
        print("Statistically significant")
    else:
        print("Not statistically significant")
    return test

In [12]:
# Alternative T-test
def t_test(counts, questions, null_value):  # Perform a one-sample t-test
    sample_mean = np.mean(counts)
    n = len(counts)
    sample_std = np.std(counts, ddof=1)  # Use sample standard deviation (ddof=1 for unbiased estimate)
    standard_error = sample_std / np.sqrt(n)
    test_statistic = (sample_mean - null_value) / standard_error
    degrees_freedom = n - 1
    p_value = scistats.t.sf(np.abs(test_statistic), df=degrees_freedom) * 2  # Two-tailed p-value
    if p_value <= 0.05:
        result = "Reject the null hypothesis. There is statistically significant evidence that the mean is different from the random choice value."
    else:
        result = "Fail to reject the null hypothesis. There is not enough statistically significant evidence that the mean is different from the random choice value."

    return test_statistic, p_value

# 1- Are the overall average success rates observed significant vs chance?

In [13]:
calculations(correct, participants[0], questions)

Participants: 65
[30 57 25 25 39 42 34 43 31 16 26 34]


(0.5154, 0.5, [25, 34])

In [14]:
t_test(correct, questions, null_value)

(10.686333220641977, 3.79373231727064e-07)

### Conclusion: All the overall average success rates observed with the exception of the astronomers group are significantly higher than the random choice probability

In [15]:
calculations(experts_correct, participants[1], questions)

Participants: 29
[15 26 11 14 20 20 16 22 15  7 12 15]


(0.5546, 0.5172, [15])

In [16]:
t_test(experts_correct, questions, null_value)

(10.497028305938942, 4.5436676622038175e-07)

In [17]:
calculations(nonexperts_correct, participants[2], questions)

Participants: 31
[12 26 11  9 17 21 16 19 14  7 13 14]


(0.4812, 0.4516, [14])

In [18]:
t_test(nonexperts_correct, questions, null_value)

(9.528499559614136, 1.1952989449600024e-06)

In [19]:
calculations(astro_correct, participants[4], questions)

Participants: 12
[ 6 12  5  5  7  9  6 10  5  6  7  6]


(0.5833, 0.5, [6])

In [20]:
t_test(astro_correct, questions, null_value)

(10.412722986808014, 4.928042565582745e-07)

In [21]:
calculations(mus_correct, participants[5], questions)

Participants: 11
[3 9 3 5 8 6 6 7 5 0 6 6]


(0.4848, 0.5455, [6])

In [22]:
t_test(mus_correct, questions, null_value)

(7.134068690619276, 1.907441655353338e-05)

In [23]:
calculations(astromus_correct, participants[3], questions)

Participants: 10
[7 7 2 5 7 7 7 8 5 1 4 5]


(0.5417, 0.6, [7])

In [24]:
t_test(astromus_correct, questions, null_value)

(8.018061344024217, 6.39360095405938e-06)

In [25]:
calculations(nonexperts_4_correct, participants[6], questions)

Participants: 12
[ 8 10  5  3  5  9  4  7  7  8  5  9]


(0.5556, 0.5833, [5])

In [26]:
t_test(nonexperts_4_correct, questions, null_value)

(9.831066239967777, 8.7628254858587e-07)

## Combined

In [27]:
null_value_comb = 0.2
combined_questions = len(combined_correct)
combined_questions

2

In [28]:
combined_correct/67

array([0.1641791 , 0.14925373])

In [29]:
t_test(combined_correct, combined_questions, null_value_comb)

(20.6, 0.030879631823023113)

In [30]:
t_test(experts_combined_correct, combined_questions, null_value_comb)

(1.72, 0.3352613336627147)

In [31]:
t_test(nonexperts_combined_correct, combined_questions, null_value_comb)

(2.9, 0.21139562263965195)

In [32]:
t_test(astromus_combined_correct, combined_questions, null_value_comb)

(2.6, 0.2337501225046868)

In [33]:
t_test(mus_combined_correct, combined_questions, null_value_comb)

(3.8, 0.16381736484967485)

In [34]:
t_test(astro_combined_correct, combined_questions, null_value_comb)

(2.6, 0.2337501225046868)

In [35]:
t_test(nonexperts_4_combined_correct, combined_questions, null_value_comb)

(2.9, 0.21139562263965195)

In [36]:
t_test(blv_combined_correct, combined_questions, null_value_comb)

/var/folders/jw/nr9685ns4r32q0t030hxmzlw0000gn/T/ipykernel_20417/1601646738.py:7: RuntimeWarning: divide by zero encountered in double_scalars
  test_statistic = (sample_mean - null_value) / standard_error


(-inf, 0.0)

In [37]:
t_test(nonblv_combined_correct, combined_questions, null_value_comb)

/var/folders/jw/nr9685ns4r32q0t030hxmzlw0000gn/T/ipykernel_20417/1601646738.py:7: RuntimeWarning: divide by zero encountered in double_scalars
  test_statistic = (sample_mean - null_value) / standard_error


(-inf, 0.0)

### Conclusion: No statistically significance

# 2- Are the differences observed in the means statistically significant?

In [38]:
f_stat, p_valor = scistats.f_oneway(experts_correct, nonexperts_correct)

print("Estadístico F:", f_stat)
print("Valor p:", p_valor)

Estadístico F: 0.2965612104539202
Valor p: 0.5915241055705412


In [39]:
# Kruskal-Wallis test: kruskal_p_value < 0.05 => reject the null hypothesis => statistical significance
H_statistic, kruskal_p_value = scistats.kruskal(experts_correct, nonexperts_correct)
print(H_statistic, kruskal_p_value)

0.4435331000291743 0.5054220894957939


### Conclusion: The differences in the means between experts and non experts are not statistically significant.

In [40]:
# T-test
stat, p_value = ttest_ind(experts_correct, nonexperts_correct, equal_var=False)
print(stat, p_value)

0.5445743387765531 0.5915262377562682


# 3- Are they meaningful?

In [41]:
# Cohen's d for Effect Size (T-test). Meaninful: Small effect size d=0.2, medium d=0.5, large d=0.8.

# Calculate means and standard deviations
mean1 = np.mean(experts_correct/participants[1])
mean2 = np.mean(nonexperts_correct/participants[2])
std1 = np.std(experts_correct, ddof=1)
std2 = np.std(nonexperts_correct, ddof=1)

# Calculate Cohen's d
cohen_d = (mean1 - mean2) / np.sqrt((std1**2 + std2**2) / 2)
print("Cohen's d:", cohen_d)

Cohen's d: 0.013990041468784796


# 4- Subgroup analysis

In [42]:
# Test normality for each group. p-value<0.05 =>not normally distributed
stat1, p1 = shapiro(astromus_correct)
stat2, p2 = shapiro(mus_correct)
stat3, p3 = shapiro(astro_correct)
stat4, p4 = shapiro(nonexperts_4_correct)

print(f"astromus normality: p={p1}")
print(f"mus normality: p={p2}")
print(f"astro normality: p={p3}")
print(f"nonexperts normality: p={p4}")

astromus normality: p=0.05495025962591171
mus normality: p=0.4459173083305359
astro normality: p=0.019538642838597298
nonexperts normality: p=0.5632864832878113


In [43]:
f_stat, p_valor = scistats.f_oneway(astromus_correct, mus_correct, astro_correct,nonexperts_4_correct)

print("Estadístico F:", f_stat)
print("Valor p:", p_valor)

Estadístico F: 1.7003069367710248
Valor p: 0.18078967509952268


In [44]:
# Kruskal-Wallis test: kruskal_p_value < 0.05 => reject the null hypothesis => statistical significance
H_statistic, kruskal_p_value = scistats.kruskal(astromus_correct, mus_correct, astro_correct, nonexperts_4_correct)
print(H_statistic, kruskal_p_value)

3.0345483109301394 0.38632911816853377


In [45]:
#alternative test: Chi square
stat, p_value = friedmanchisquare(astromus_correct, mus_correct, astro_correct, nonexperts_4_correct)
print(stat, p_value)

5.037735849056623 0.16905470279825174


### Post-hoc analysis

In [46]:
# Dunn test with Bonferroni correction (6 comparisons => alpha = 0.05/6 = 0.0083)
dunn_result = sp.posthoc_dunn([astromus_correct, mus_correct, astro_correct, nonexperts_4_correct], p_adjust='bonferroni')

# Label the groups
dunn_result.index = ['astromus', 'mus', 'astro', 'nothing']
dunn_result.columns = ['astromus', 'mus', 'astro', 'nothing']

print(dunn_result)

          astromus  mus  astro  nothing
astromus       1.0  1.0    1.0      1.0
mus            1.0  1.0    1.0      1.0
astro          1.0  1.0    1.0      1.0
nothing        1.0  1.0    1.0      1.0


## Conclusion: The differences in the overall average success rates are not statistically significant

In [47]:
# Cohen's d for Effect Size (T-test). Meaninful: Small effect size d=0.2, medium d=0.5, large d=0.8.

# Calculate means and standard deviations
mean1 = np.mean(astromus_correct/participants[4])
mean2 = np.mean(astro_correct/participants[5])
std1 = np.std(mus_correct, ddof=1)
std2 = np.std(astro_correct, ddof=1)

# Calculate Cohen's d
cohen_d = (mean1 - mean2) / np.sqrt((std1**2 + std2**2) / 2)
print("Cohen's d:", cohen_d)

Cohen's d: -0.07964516418558333


In [48]:
# Cohen's d for Effect Size (T-test). Meaninful: Small effect size d=0.2, medium d=0.5, large d=0.8.

# Calculate means and standard deviations
mean1 = np.mean(nonexperts_4_correct/participants[4])
mean2 = np.mean(astro_correct/participants[5])
std1 = np.std(mus_correct, ddof=1)
std2 = np.std(astro_correct, ddof=1)

# Calculate Cohen's d
cohen_d = (mean1 - mean2) / np.sqrt((std1**2 + std2**2) / 2)
print("Cohen's d:", cohen_d)

Cohen's d: -0.0347937918626439


# BLV Analysis

In [49]:
calculations(blv_correct, participants[7], questions)

Participants: 2
[1 2 0 0 2 1 1 2 2 0 1 1]


(0.5417, 0.5, [1])

In [50]:
t_test(blv_correct, questions, null_value)

(3.2472980427292546, 0.007772467048837831)

### Conclusion: The BLV average success rate difference with the random choice probability is statistically significant.

In [51]:
calculations(nonblv_correct, participants[8], questions)

Participants: 2
[2 2 0 1 1 1 1 2 2 1 0 1]


(0.5833, 0.5, [1])

In [52]:
t_test(nonblv_correct, questions, null_value)

(3.9898223460376245, 0.002122823820319628)

In [53]:
# Kruskal-Wallis test: kruskal_p_value < 0.05 => reject the null hypothesis => statistical significance
H_statistic, kruskal_p_value = scistats.kruskal(blv_correct, nonblv_correct)
print(H_statistic, kruskal_p_value)

0.062078272604581555 0.8032407957714518


### Conclusion: The differences between BLV and non BLV average success rates are not statistically significant.